# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.TimeStampModel')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('books.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.TimeStampModel')),
                ('slug', models.CharField(max_length=255)),
                ('isbn13', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn10', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=255)),
                ('edition', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, upload_to='images')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ManyToManyField(null=True, to='books.Author')),
            ],
            bases=('books.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.TimeStampModel')),
                ('slug', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Category')),
            ],
            bases=('books.timestampmodel',),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='books.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
