# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.TimeStampModel')),
            ],
            bases=('books.timestampmodel',),
        ),
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
