# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160819_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
