# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160819_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(null=True, to='books.Category'),
        ),
    ]
